# Generated by Django 4.0.5 on 2022-06-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now=True, verbose_name='Дата заказа')),
                ('name', models.CharField(max_length=200, verbose_name='Имя заказчика')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. почта заказчика')),
                ('order_phone', models.CharField(max_length=200, verbose_name='Телефон заказчика')),
            ],
        ),
    ]
